services:
  backend:
    build:
      context: ./backend
      dockerfile: ClinicScheduling.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./data:/app/data
    networks:
      - clinic-network

  frontend:
    build:
      context: ./frontend/clinic-scheduling-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  clinic-data:
